title: Thurman Brown Consultant Inc.
description: Pioneering Excellence in Addiction Care

url: "https://digitalsparkhq.github.io"   # your GitHub username’s domain
baseurl: "/Websiteforthurmanbrown"        # repo name
